name: 👀 Check

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  check:
    name: 👀 Check
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v6

      - name: 🛠️ Setup node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json
          cache: pnpm

      - name: 🚚 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🚀 Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: ⚡ Run checks with turbo (lint, format, type-check)
        run: pnpm run check
